# Generated by Django 5.1.7 on 2025-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0003_remove_bus_available_seats_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='bus_app.seat'),
        ),
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
