# Generated by Django 5.1.7 on 2025-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0004_remove_booking_seat_count_booking_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_count',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
