# Generated by Django 5.1.7 on 2025-03-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bus_route_booking_bus_route_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
